name: Build Scoped Rector

# builds the content of https://github.com/rectorphp/rector-prefixed
on:
    push:
        branches:
            - master
    pull_request: null
    release:
        types:
            - published

jobs:
    build_scoped_rector:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    # this must be PHP 7.4, as phpstan-src requires it
                    php-version: 7.4
                    tools: composer:v2
                # fixes https://github.com/rectorphp/rector/pull/4559/checks?check_run_id=1359814403, see https://github.com/shivammathur/setup-php#composer-github-oauth
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # 1. prepare dependencies
            # replace phpstan.phar with phpstan-src, see https://github.com/phpstan/phpstan-src
            -   run: composer remove phpstan/phpstan --no-update
            -   run: composer config repositories.repo-name vcs https://github.com/phpstan/phpstan-src.git
            -   run: composer require phpstan/phpstan-src:@dev --no-update
            # mimics PHPStan https://github.com/phpstan/phpstan-src/blob/d3be969b13654394d0186b9597449d44477f0012/composer.json#L17
            -   run: composer require jetbrains/phpstorm-stubs:dev-master#05d145c0bbafcf9a551fdd8824adb2a7e259fdaf --no-update

            -   run: composer update --no-progress --ansi

            # downgrade PHPStan code to PHP 7.2
            -   run: bin/rector process vendor/phpstan/phpstan-src/src --config ci/downgrade-phpstan-php74-rector.php --ansi

            -   run: vendor/bin/package-scoper scope-composer-json composer.json --ansi
            # see https://github.com/humbug/php-scoper#without-box
            -   run: composer update --no-dev --prefer-dist --ansi

            # 2. scope it
            -   run: wget https://github.com/humbug/php-scoper/releases/download/0.13.8/php-scoper.phar
            -   run: php php-scoper.phar add-prefix bin config packages rules src stubs tests templates vendor composer.json --output-dir rector-scoped scoper.inc.php --force --ansi
            -   run: composer dump-autoload --working-dir rector-scoped --ansi --optimize --classmap-authoritative

            # 3. run it
            -   run: chmod 777 rector-scoped/bin/rector

            # 4. get tag - see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            # 5. publish it to remote repository
            -
                # Uses an action in the root directory
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'rector-scoped'
                    split-repository-organization: 'rectorphp'
                    split-repository-name: 'rector-prefixed'
                    tag: ${{ steps.previous_tag.outputs.tag }}
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
